// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQQL6by3n7mY5YBJueNcI6xDuPuCtoQc',
    appId: '1:212074483378:web:2dfe20cff52137bdcc43ab',
    messagingSenderId: '212074483378',
    projectId: 'poll-app-d6daf',
    authDomain: 'poll-app-d6daf.firebaseapp.com',
    storageBucket: 'poll-app-d6daf.firebasestorage.app',
    measurementId: 'G-9N9047RJT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQeVAm8KE9vq0XSaBBsLnkdb0vZCl1YLU',
    appId: '1:212074483378:android:3b9b707016ac005bcc43ab',
    messagingSenderId: '212074483378',
    projectId: 'poll-app-d6daf',
    storageBucket: 'poll-app-d6daf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSJQ86F_PbzqmBcEdN92CLoA8xP9aAo1Q',
    appId: '1:212074483378:ios:b8a347902de84ca6cc43ab',
    messagingSenderId: '212074483378',
    projectId: 'poll-app-d6daf',
    storageBucket: 'poll-app-d6daf.firebasestorage.app',
    iosBundleId: 'com.example.pollApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSJQ86F_PbzqmBcEdN92CLoA8xP9aAo1Q',
    appId: '1:212074483378:ios:b8a347902de84ca6cc43ab',
    messagingSenderId: '212074483378',
    projectId: 'poll-app-d6daf',
    storageBucket: 'poll-app-d6daf.firebasestorage.app',
    iosBundleId: 'com.example.pollApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLQQL6by3n7mY5YBJueNcI6xDuPuCtoQc',
    appId: '1:212074483378:web:4635a8b99ae80f70cc43ab',
    messagingSenderId: '212074483378',
    projectId: 'poll-app-d6daf',
    authDomain: 'poll-app-d6daf.firebaseapp.com',
    storageBucket: 'poll-app-d6daf.firebasestorage.app',
    measurementId: 'G-1SWQ6TC3RM',
  );
}
